saleor/saleor-storefront

.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

- Added PR templates
- Added Code of Conduct
- Added issue template
Pretty much copy paste of Saleor's, let me know if we're missing anything

Add github templates

---

src/components/ProductDescription/index.tsx

Products with no attributes were not rendering 
close #106

111 / Fix products with no attributes

---

src/components/ProductDescription/index.tsx
src/components/ProductPage/index.tsx

114 / Update variant's price on variant's change

---

apollo.config.js

This config allows using the [Apollo GraphQL](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo) extension for VSCode which enables schema introspection and validation within `gql` tags.

Add Apollo config

---

src/components/HomePage/index.tsx
src/components/HomePage/scss/index.scss

Improve homepage mobile view

---

src/components/Overlay/index.tsx
src/components/Overlay/scss/index.scss
src/components/ProductListItem/index.tsx
src/components/ProductListItem/scss/index.scss
src/components/ProductsList/scss/index.scss
src/components/SearchOverlay/index.tsx
src/components/SearchOverlay/scss/index.scss
src/core/config.ts

I want to merge this change because it fixes various visual things in project, like search bar and product list.

Minor visual fixes

---

package-lock.json
package.json
src/index.tsx

Resolves #131 
Blocked by https://github.com/mirumee/saleor/issues/3256

Use query batching

---

src/components/ProductPage/index.tsx
src/components/ProductPage/queries.ts
src/core/types/index.ts
src/core/types/saleor.ts

Update queries after migrating connections to lists #153

Fixed: Update queries after migrating connections to lists #153

---

src/components/MainMenu/index.tsx

This fixes https://github.com/mirumee/saleor-storefront/issues/155 temporarily otherwise the page will crach.
We should fully support menu with url, page, category and collection later.

Do not render menu which has not category

---

src/components/Footer/index.tsx
src/components/HomePage/index.tsx
src/components/HomePage/queries.ts
src/components/NavigationOverlay/queries.ts
src/core/types/saleor.ts
src/core/utils.ts
src/views/Category/index.tsx
src/views/Category/queries.ts
src/views/Search/index.tsx
src/views/Search/queries.ts

Fix sort by param

---

src/components/Footer/queries.ts
src/components/HomePage/queries.ts
src/components/NavigationOverlay/queries.ts
src/components/ProductPage/queries.ts
src/views/Category/queries.ts
src/views/Search/queries.ts

Adding `first` or `last` parameters to all queries to prepare for changes in backend:
https://github.com/mirumee/saleor/pull/3352

Add pagination for all queries

---

apollo.config.js

This PR changes the Apollo config to fetch data from Apollo Engine.

Add configuration for Apollo Engine

---

.circleci/config.yml

This PR should fix deployment from tags.

Ignore branches in deploy task

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Add changelog file

---

src/components/ProductPage/scss/index.scss

Fix product page talet view

---

CHANGELOG.md
src/components/Button/scss/index.scss
src/components/CheckoutShippingOptions/index.tsx

Block continue to billing without shipement chosen

---

src/components/App/scss/_animations.scss
src/components/Overlay/scss/index.scss
src/components/OverlayManager/Cart/scss/index.scss

Fix cart overlay footer visibility in firefox

---

src/checkout/provider.tsx
src/checkout/views/Payment/View.tsx
src/checkout/views/Review/View.tsx
src/checkout/views/Shipping/View.tsx

I want to merge this change because it fixes:
- redirecting bug after payment step,
- Use as Billing Address checkbox

Checkout fixes

---

CHANGELOG.md
src/checkout/context.tsx
src/checkout/provider.tsx
src/components/ProductDescription/AddToCart.tsx
src/components/ProductDescription/index.tsx

Add checkout creation for logged in users without checkout upon adding to cart

---

CHANGELOG.md
package-lock.json
src/checkout/queries.ts
src/checkout/types/Checkout.ts
src/checkout/types/CheckoutLine.ts
src/checkout/types/createCheckout.ts
src/checkout/types/getCheckout.ts
src/checkout/types/getUserCheckout.ts
src/checkout/types/updateCheckoutLine.ts
src/checkout/views/Billing/types/updateCheckoutBillingAddress.ts
src/checkout/views/Shipping/types/updateCheckoutShippingAddress.ts
src/checkout/views/ShippingOptions/types/updateCheckoutShippingOptions.ts
src/components/CartTable/ProductRow.tsx
src/components/CartTable/scss/index.scss
src/components/ProductDescription/index.tsx
src/images/cart-add-disabled.svg
src/views/Product/queries.ts

Stock quantity check in cart page

---

CHANGELOG.md
src/checkout/index.tsx
src/checkout/scss/index.scss
src/checkout/views/Review/View.tsx
src/checkout/views/Review/queries.ts
src/checkout/views/Review/types/completeCheckout.ts
src/components/App/index.tsx
src/components/App/routes.tsx
src/components/Button/scss/index.scss
src/core/utils.ts
src/views/OrderConfirmation/View.tsx
src/views/OrderConfirmation/scss/index.scss

Add order confirmation page

---

src/views/OrderConfirmation/View.tsx

A few typos noted in #263 and added a bit more energy to the title.

Fix typos in the order confirmation page

---

src/components/OverlayManager/Manager.tsx

Makes it easier to recognize the component in devtools

Made component name consistent with the aliases

---

src/storybook/.babelrc

This file is required for storybook

create .babelrc as per required

---

src/components/OverlayManager/Password/index.tsx

add `overlay__header-text` class to title of password overlay

password overlay update

---

src/views/Product/Page.tsx

create const cartContextConsumer and assign CardContext.Consumer for remove repetition of same CardContext.Consumer

const cartContextConsumer added for remove repetition

---

src/components/OverlayManager/Login/index.tsx

tag change as per requirement

---

CHANGELOG.md
package-lock.json
src/components/CachedImage/CachedImage.tsx

Fix images cors

---

src/components/App/routes.tsx

removed duplication of url rules

remove duplication of url rules

---

CHANGELOG.md
src/components/OverlayManager/Cart/Cart.tsx

Fix for #286 where number of cart items wasn't reflecting the actual total quantity of all products

Fix for cart counter

---

src/views/Product/Page.tsx

Product Page - fix scroll bug  on firefox

---

src/components/MainMenu/scss/index.scss

Cart icon - change width to min-width

---

src/components/ProductDescription/index.tsx

set min value to 1 in add to cart quantity

set min value to 1 in quantity

---

CHANGELOG.md
src/components/App/scss/variables.scss
src/components/ProductDescription/index.tsx
src/components/ProductDescription/scss/index.scss
src/components/SelectField/index.tsx
src/components/SelectField/scss/index.scss
src/components/ShippingAddressForm/scss/index.scss
src/components/TextField/index.tsx
src/components/TextField/scss/index.scss

New styles for inputs

---

CHANGELOG.md
package-lock.json
src/core/SEO/Homepage/structuredData.tsx
src/core/SEO/Product/structuredData.tsx
src/userAccount/views/OrderDetails/types/OrderById.ts
src/userAccount/views/OrderDetails/types/OrderByToken.ts
src/userAccount/views/OrderDetails/types/OrderDetail.ts
src/views/Category/types/Category.ts
src/views/Collection/types/Collection.ts
src/views/Home/Page.tsx
src/views/Home/View.tsx
src/views/Product/Page.tsx
src/views/Product/queries.ts
src/views/Product/types/ProductDetails.ts
src/views/Product/types/ProductVariantFields.ts
src/views/Product/types/VariantList.ts
src/views/Search/types/SearchProducts.ts
types/globalTypes.ts

fixes #297 
This can be tested using https://search.google.com/structured-data/testing-tool/u/0/
TODO:

Add schema.org structured data to homepage and product details

---

src/components/CheckoutLogin/index.tsx

It removes unnecessary console.log from code

Remove console log from code

---

src/components/Select/Select.tsx
src/components/Select/scss/index.scss

Fix select options position

---

CHANGELOG.md
src/components/Breadcrumbs/index.tsx
src/components/Breadcrumbs/scss/index.scss
src/components/Footer/scss/index.scss
src/globalStyles/scss/_utils.scss
src/globalStyles/scss/index.scss

typographical changes

---

src/components/MainMenu/MainMenu.tsx
src/components/MenuDropdown/scss/index.scss

Add links to dropdown menu for accessing user account pages

Add new links to users dropdown menu

---

CHANGELOG.md
src/checkout/components/CreditCardForm/CreditCardForm.tsx
src/checkout/components/CreditCardForm/customTypes.ts
src/checkout/components/CreditCardForm/index.ts
src/checkout/components/index.ts
src/checkout/views/Payment/Gateways/Braintree/CreditCard.tsx
src/checkout/views/Payment/Gateways/Braintree/scss/index.scss
src/core/payments/braintree.ts
src/core/utils.ts

Fix credit card form labels

---

CHANGELOG.md
package-lock.json
package.json
src/sitemap-builder.ts
src/sitemap/SitemapGenerator.ts
src/sitemap/fetchItems.ts
src/sitemap/index.ts
src/sitemap/queries.ts
webpack.config.js

Sitemap generator

---

.circleci/config.yml
package-lock.json
src/components/NotFound/index.tsx
src/components/OverlayManager/Search/Search.tsx
src/core/payments/braintree.ts
src/core/utils.ts
src/hooks/useClickedOutside.tsx
src/index.tsx
tsconfig.json
tslint.json

Codebase improvements

---

src/index.tsx

This PR fixes GraphQL URL when no BACKEND_URL provided.

Fix default api url

---

README.md
package-lock.json
package.json
src/index.tsx
src/sw.js
src/views/Product/Page.tsx
webpack.config.js

Service worker improvements

---

src/sw.js

Exclude api and dashboard urls from precaching

---

.circleci/config.yml
package-lock.json
package.json
tsconfig.json
webpack.config.js

Run TS typechecker on separate process

---

config/webpack/config.base.js
config/webpack/config.dev.js
config/webpack/config.prod.js
config/webpack/config.worker.js
package-lock.json
package.json
src/app/App.tsx
src/history.ts
src/index.tsx
webpack.config.js

Use webpacks hot module replacement feature

---

src/components/ProductDescription/index.tsx

Add to basket allows for negative quantity to be selected

---

.storybook/__tests__/__snapshots__/storyshots.test.js.snap
.storybook/__tests__/storyshots.test.js

This fixes storyshoots config so the class names in shots are not randomized so changes in theme wont cause changes in random places due to class name updates

Update storyshoots config for jest to have non-random class names

---

.storybook/__tests__/__snapshots__/storyshots.test.js.snap
CHANGELOG.md
package-lock.json
package.json
src/@next/components/atoms/RichTextContent/RichTextContent.tsx
src/@next/components/atoms/RichTextContent/fixtures/default_text_block.ts
src/@next/components/atoms/RichTextContent/fixtures/headers.ts
src/@next/components/atoms/RichTextContent/fixtures/list.ts
src/@next/components/atoms/RichTextContent/fixtures/text_blocks.ts
src/@next/components/atoms/RichTextContent/index.ts
src/@next/components/atoms/RichTextContent/stories.tsx
src/@next/components/atoms/RichTextContent/test.tsx
src/@next/components/atoms/RichTextContent/types.ts
src/@next/components/atoms/index.ts
src/views/Product/Page.tsx
src/views/Product/View.tsx
src/views/Product/queries.ts
src/views/Product/types/ProductDetails.ts

Use JSON fields for rendering rich-text content

---

src/@next/components/atoms/RichTextContent/RichTextContent.tsx
webpack.d.ts

fixes compilation errors for draftjs library

Fix draftjs issues

---

src/components/CheckoutLogin/CheckoutAsGuest.tsx
src/components/LoginForm/index.tsx

Just fixed a couple of simple typos that were bugging me

Fixed typos

---

package.json

Don't record cypress test data by default

---

.storybook/__tests__/__snapshots__/storyshots.test.js.snap
src/@next/components/organisms/CreditCardForm/CreditCardForm.tsx
src/@next/components/organisms/CreditCardForm/CreditCardFormContent.tsx
src/@next/components/organisms/CreditCardForm/stories.tsx
src/@next/components/organisms/CreditCardForm/test.tsx
src/@next/components/organisms/CreditCardForm/types.ts
src/index.tsx

CreditCardForm small fixes

---

CHANGELOG.md
src/@next/components/atoms/ButtonLink/ButtonLink.tsx
src/@next/components/atoms/ButtonLink/__snapshots__/stories.storyshot
src/@next/components/atoms/ButtonLink/index.ts
src/@next/components/atoms/ButtonLink/stories.tsx
src/@next/components/atoms/ButtonLink/styles.ts
src/@next/components/atoms/ButtonLink/test.tsx
src/@next/components/atoms/ButtonLink/types.ts
src/@next/components/atoms/Input/__snapshots__/stories.storyshot
src/@next/components/atoms/Input/styles.ts
src/@next/components/atoms/TileGrid/__snapshots__/stories.storyshot
src/@next/components/atoms/index.ts
src/@next/components/molecules/TextField/__snapshots__/stories.storyshot
src/@next/globalStyles/themes.ts

ButtonLink component

---

src/checkout/components/UserAddressSelector/UserAddressSelector.tsx
src/checkout/types.ts
src/checkout/views/Billing/Page.tsx
src/checkout/views/Shipping/Page.tsx

Address validation in checkout fails but doesn't show any errors 

---

.circleci/config.yml
README.md
package.json

Because we keep all compiled translation files inside the repository we don't need to run extra commands on CircleCI.

Remove unnecessary CircleCI step

---

config/webpack/config.base.js

This PR sets the default values of the env variables.

Set default values of env variables

---

CHANGELOG.md
src/@next/components/atoms/Button/Button.tsx
src/@next/components/atoms/Button/__snapshots__/stories.storyshot
src/@next/components/atoms/Button/stories.tsx
src/@next/components/atoms/Button/styles.ts
src/@next/components/atoms/Button/test.tsx
src/@next/components/atoms/Button/types.ts
src/@next/components/atoms/ButtonLink/__snapshots__/stories.storyshot
src/@next/components/atoms/ButtonLink/styles.ts
src/@next/components/molecules/FormFooter/FormFooter.tsx
src/@next/components/molecules/FormFooter/__snapshots__/stories.storyshot
src/@next/components/molecules/FormFooter/index.ts
src/@next/components/molecules/FormFooter/stories.tsx
src/@next/components/molecules/FormFooter/styles.ts
src/@next/components/molecules/FormFooter/test.tsx
src/@next/components/molecules/FormFooter/types.ts
src/@next/components/molecules/index.ts
src/@next/globalStyles/constants.ts
src/@next/globalStyles/themes.ts
src/components/Modal/Modal.tsx

FormFooter component

---

src/@next/components/molecules/CardHeader/CardHeader.tsx
src/@next/components/molecules/CardHeader/__snapshots__/stories.storyshot
src/@next/components/molecules/CardHeader/index.ts
src/@next/components/molecules/CardHeader/stories.tsx
src/@next/components/molecules/CardHeader/styles.ts
src/@next/components/molecules/CardHeader/test.tsx
src/@next/components/molecules/CardHeader/types.ts
src/@next/components/molecules/index.ts
src/@next/globalStyles/constants.ts
src/@next/globalStyles/global.ts

CardHeader component

---

src/views/Account/Account.tsx

This PR redirects unauthorized users to the base URL when the current page is private.

Redirect when unauthorized user

---

README.md

Fix path to the license file

---

src/@next/utils/misc.ts

Adds overload types for better static return types

Improve maybe utility types

---

src/@sdk/react/components/CredentialsProvider/CredentialsProvider.tsx

Fix the auto-login process

---

src/@next/components/atoms/Button/Button.tsx
src/@next/components/atoms/Button/__snapshots__/stories.storyshot
src/@next/components/atoms/Button/stories.tsx
src/@next/components/atoms/Button/styles.ts
src/@next/components/atoms/Button/types.ts
src/@next/components/atoms/ButtonLink/__snapshots__/stories.storyshot
src/@next/components/atoms/ButtonLink/styles.ts
src/@next/components/atoms/Message/__snapshots__/stories.storyshot
src/@next/components/atoms/NotificationTemplate/__snapshots__/stories.storyshot
src/@next/components/atoms/SocialMediaIcon/__snapshots__/stories.storyshot
src/@next/components/molecules/FormFooter/__snapshots__/stories.storyshot
src/@next/components/organisms/Modal/__snapshots__/stories.storyshot
src/@next/globalStyles/constants.ts

Adjust styles to the new design

---

src/@sdk/react/components/CredentialsProvider/CredentialsProvider.tsx

This PR allows to auto-login the user when this option is enabled in the browser settings.

Auto login user when available

---

src/globalStyles/scss/variables.scss

Fix font family typo

---

CHANGELOG.md
src/views/Article/Page.tsx
src/views/Article/View.tsx
src/views/Article/query.ts
src/views/Article/types/Article.ts

I want to merge this change because I had noticed that the pages didn't seem to be updating from the Dashboard as the products did. I tried to mimic the way the products were updated to retrieve and display data.
The original issue number was #361  .
This is my first pull request. If I've made any mistakes, please let me know kindly. Happy to contribute if I can!

Use JSON fields for rendering rich-text content on Pages

---

src/@sdk/index.ts
src/@sdk/queries/index.ts
src/@sdk/react/types.ts
src/@sdk/react/useQuery.ts
src/@sdk/types.ts
src/@sdk/utils.ts

[sdk] Use watchQuery instead of regular apollo query

---

src/sw.js

Add urls without ending slash to blacklist

---

src/components/MenuDropdown/scss/index.scss

Move the user menu to the foreground

---

src/views/Category/queries.ts
src/views/Collection/queries.ts

Avoid deprecated fields in queries

---

src/@sdk/react/useQuery.ts

Unsubscribe from previous observable after skip value change

---

src/@sdk/react/useQuery.ts

Fix unsubscriber side effect

---

src/@sdk/index.ts
src/@sdk/queries/checkout.ts
src/checkout/components/UserAddressSelector/UserAddressSelector.tsx
src/checkout/types.ts
src/checkout/views/Billing/Page.tsx
src/checkout/views/Shipping/Page.tsx

Shipping address page improvements

---

README.md

Current method fails for most users.

Use standard github url for cloning repo

---

package.json

This updates package.json to include latest node modules version as current one would result in an error.
```
/home/user/.node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
311 |   declarator __attribute__((deprecated(message)))
|   ^~~~~~~~~~
make: *** [binding.target.mk:125: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/user/.work/saleor-storefront/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.work/saleor-storefront/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit …
```

Update node modules version for build

---

package-lock.json
src/@sdk/index.ts
src/@sdk/react/useQuery.ts
src/@sdk/tsHelpers.ts
src/@sdk/utils.ts

[sdk] Implement loadMore

---

src/@next/components/views/OrdersHistory/OrdersHistory.tsx
src/@next/components/views/OrdersHistory/styles.ts

It adds load more button on order list so the user can load more orders

Add load more button to order history

---

package-lock.json
src/@next/components/atoms/Select/Select.tsx
src/@next/components/atoms/Select/__snapshots__/stories.storyshot
src/@next/components/atoms/Select/styles.ts
src/@next/components/atoms/TileGrid/TileGrid.tsx
src/@next/components/molecules/OrderTabel/OrderTabel.tsx
src/@next/components/molecules/OrderTabel/__snapshots__/stories.storyshot
src/@next/components/molecules/OrderTabel/styles.ts
src/@next/components/organisms/AddressForm/__snapshots__/stories.storyshot

it fixes errors and warnings in  Account page

Fix console errors and warnings

---

static.json

This PR enables push-state URLs on Heroku using [custom routes](https://github.com/heroku/heroku-buildpack-static#custom-routes).
Fixes #469

Enable push-state URLs on Heroku

---

CHANGELOG.md
README.md
config/webpack/config.base.js
cypress.json
cypress/integration/main_menu/login_form.js
cypress/integration/main_menu/search.js
cypress/support/login/index.js
src/constants.ts
src/sitemap/fetchItems.ts

This PR replaces BACKEND_URL in favor of API_URI.
Fixes #472

Replace BACKEND_URL with API_URI

---

README.md
app.json

This PR improves and simplifies the application installation process on Heroku.

Heroku integration improvements

---

src/@sdk/index.ts
src/@sdk/react/helpers.ts
src/@sdk/react/useQuery.ts
src/checkout/CheckoutProvider.tsx
src/checkout/views/Shipping/Page.tsx
src/components/MainMenu/MainMenu.tsx
src/components/OverlayManager/Cart/Cart.tsx
src/components/ProductDescription/AddToCart.tsx
src/index.tsx
src/views/Account/Account.tsx

This PR gets rid of the usage of the deprecated UserProvider and improves queries state.

Logged user improvements

---

src/@sdk/queries/user.ts

This PR adapts `orderByToken.token` type to the changes from https://github.com/mirumee/saleor/pull/4758.

Change token type in `orderByToken` query

---

_redirects

Netlify redirects enables using React router for each URL.

Enable Netlify redirects

---

src/components/EmptyCart.tsx
src/components/OverlayManager/Cart/Empty.tsx

it fixes a minor typo in the Cart component.

Fixed typo in EmptyCart

---

Dockerfile
nginx/default.conf

I want to merge this change because :
- Add Dockerfile for production
- Nginx for serve the file generated by `npm run build`
Quick tutorial
```bash
$ docker build -t saleor-storefront .
$ docker run --name saleor-storefront -p 3000:80 -d saleor-storefront:latest
```

add Dockerfile and nginx conf

---

.github/stale.yml

Update config to have an exemption label for valid issues that are old and will be worked on.

Update Stalebot config

---

src/components/TextField/scss/index.scss

It fixes inputs on safari(Ios) so they are not rounder

Fix rounded inputs on safari

---

src/checkout/index.tsx
src/checkout/queries.ts
src/checkout/routes/CheckoutRoutes.tsx
src/checkout/routes/index.ts
src/checkout/routes/paths.ts
src/checkout/views/Review/Summary.tsx
src/checkout/views/Review/View.tsx

Fixes in checkout:
- lack of redirection to selected step (1,2,3,4) when clicked on step title
- in 5th step (i.e. review order) when clicked on edit icon redirection to edition of given step.

Fix lack of redirection to selected step of checkout

---

src/@next/components/molecules/ProductTile/ProductTile.tsx
src/@next/components/molecules/ProductTile/__snapshots__/stories.storyshot
src/@next/components/molecules/ProductTile/fixtures.ts
src/@next/components/molecules/ProductTile/index.ts
src/@next/components/molecules/ProductTile/stories.tsx
src/@next/components/molecules/ProductTile/styles.ts
src/@next/components/molecules/ProductTile/test.tsx
src/@next/components/molecules/ProductTile/types.ts
src/@next/components/molecules/Thumbnail/Thumbnail.tsx
src/@next/components/molecules/Thumbnail/types.ts
src/@next/components/molecules/index.ts

Add product tile component - it might replace product item component in the future.

Add new product tile

---

src/core/config.ts

It fixes meta-tags and page title

Update meta description and fix title to match the homepage's pattern

---

webpack.config.js

Add support for reading environment variables from `.env`file - fix #595

Read environment variables from dotenv file

---

src/components/OverlayManager/Login/RegisterForm.tsx

I want to merge this change because it improves the way account confirm URL is being created.
(in addition to https://github.com/mirumee/saleor/issues/1527)

Fullfill account confirm URL with path

---

Dockerfile.dev

I want to merge this change because it adds a dockerfile for development. We will need that in order to create saleor platform (under which one can run entire project with a single command).

Add dockerfile for development purposes

---

src/components/Meta/consumer.tsx

It fixes description and title of a product when sharing on sites which use open graph protocol

Fix open graph tags

---

src/@next/components/molecules/ProductTile/__snapshots__/stories.storyshot
src/@next/components/molecules/ProductTile/styles.ts
src/@next/components/organisms/ProductList/__snapshots__/stories.storyshot

I want to merge this change because... it just fixes product list responsiveness.

Fix product list responsivness

---

src/@next/components/organisms/ProductGallery/__snapshots__/stories.storyshot
src/@next/components/organisms/ProductGallery/styles.ts
src/components/ProductDescription/scss/index.scss
src/views/Product/scss/index.scss

Product Gallery was not scaling down on changing width of screen to smaller.
Add to Cart button was not scaled down

Fix styling on product page

---

src/views/Product/queries.ts

This removes fetching of category details when retrieving other products within the same category as the product being viewed.
Closes https://github.com/mirumee/saleor-storefront/issues/618

Removed a unneeded query to category details of sub-products

---

src/@next/components/molecules/ProductDescription/ProductDescription.tsx
src/@next/components/organisms/ProductGallery/ProductGallery.tsx

I want to merge this change because... it adds missing key attributes for lists.

Add missing key attributes for lists

---

.circleci/config.yml
cypress/integration/main_menu/login_form.js
lighthouserc.json
package-lock.json
package.json

Add lighthouse config

---

src/@sdk/auth.ts
src/@sdk/index.ts
src/@sdk/react/components/CredentialsProvider/CredentialsProvider.tsx
src/@sdk/react/helpers.ts
src/@sdk/react/mutations.ts
src/checkout/context.tsx
src/components/LoginForm/index.tsx
src/components/MainMenu/MainMenu.tsx

I want to merge this change because...it adds deleting local storage and contexts cache on user log out.

Clear cache on logout

---

src/views/Account/Account.tsx

I want to merge this change because...it fixes #520

Fix crash address book on logout

---

package-lock.json
src/@sdk/global.d.ts
src/checkout/views/Payment/Gateways/Braintree/CreditCard.tsx
src/checkout/views/Payment/Gateways/Dummy.tsx
src/checkout/views/Payment/Gateways/Stripe/CardForm.tsx
src/checkout/views/Payment/Gateways/Stripe/Stripe.tsx
src/checkout/views/Payment/View.tsx
src/core/config.ts
src/index.html
webpack.d.ts

I want to merge this change because... it fixes #521 Load time decreased from about 5-6s to 4s.

Load Stripe asynchronously

---

src/@sdk/index.ts
src/@sdk/react/components/CredentialsProvider/CredentialsProvider.tsx
src/@sdk/react/useMutation.ts
src/checkout/views/OrderConfirmation/View.tsx
src/core/utils.ts
src/views/OrderConfirmation/View.tsx

When i running the project i got a compile error message.
so i changed it for remove typescript compile errors.

remove typescript type ERROR

---

config/webpack/config.base.js
src/components/Meta/consumer.tsx
src/index.html

It adds preconnect link to graphql api for the sake of lighthouse report

Preconnect to Graphql API_URI

---

package-lock.json
package.json

It adds support for latest typescript version 🚀

Upgrade tslint to 3.8.2

---

src/checkout/views/ShippingOptions/View.tsx

I want to merge this change because the method is spelled incorrectly and it triggers my nerdy OCD.

fix: handleShippngChange spelling

---

cypress/integration/user_account/accessing_user_account_views.js
src/app/routes/AppRoutes.tsx
src/app/routes/paths.ts
src/components/MainMenu/MainMenu.tsx
src/views/Account/Account.tsx

I want to merge this change because... it hides payment options link in top menu and account menu, as it has not implemented functionality yet #653.

Hide payment options

---

src/@next/components/organisms/BraintreePaymentGateway/BraintreePaymentGateway.tsx
src/@next/components/organisms/BraintreePaymentGateway/stories.tsx
src/@next/components/organisms/BraintreePaymentGateway/test.tsx
src/@next/components/organisms/BraintreePaymentGateway/types.ts
src/@next/components/organisms/CheckoutPayment/CheckoutPayment.tsx
src/@next/components/organisms/CheckoutPayment/stories.tsx
src/@next/components/organisms/CheckoutPayment/test.tsx
src/@next/components/organisms/CheckoutPayment/types.ts
src/@next/components/organisms/PaymentGatewaysList/PaymentGatewaysList.tsx
src/@next/components/organisms/PaymentGatewaysList/stories.tsx
src/@next/components/organisms/PaymentGatewaysList/test.tsx
src/@next/components/organisms/PaymentGatewaysList/types.ts
src/@next/components/organisms/StripePaymentGateway/StripePaymentGateway.tsx
src/@next/components/organisms/StripePaymentGateway/stories.tsx
src/@next/components/organisms/StripePaymentGateway/test.tsx
src/@next/components/organisms/StripePaymentGateway/types.ts
src/@next/components/templates/Checkout/Checkout.tsx
src/@next/components/templates/Checkout/styles.ts
src/@next/components/templates/Checkout/types.ts
src/@next/pages/CheckoutPage/CheckoutPage.tsx
src/@next/pages/CheckoutPage/subpages/CheckoutAddressSubpage.tsx
src/@next/pages/CheckoutPage/subpages/CheckoutPaymentSubpage.tsx
src/@next/pages/CheckoutPage/subpages/CheckoutReviewSubpage.tsx
src/@next/pages/CheckoutPage/subpages/CheckoutShippingSubpage.tsx

I want to merge this change because it adds loading indicator when forms submiting is in progress in the checkout steps.

Add loading to checkout

---

src/@next/components/organisms/CheckoutReview/CheckoutReview.tsx
src/@next/components/organisms/CheckoutReview/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutReview/styles.ts
src/@next/components/organisms/CheckoutReview/types.ts
src/@next/pages/CheckoutPage/subpages/CheckoutReviewSubpage.tsx
src/@sdk/jobs/Cart/CartQueuedJobs.ts

I want to merge this change because it fixes wrong calculation of final checkout prices when product was added or deleted from the cart and while percentage discount was applied. It made impossible to complete checkout.

Fix wrong price calculation on cart modification

---

config/webpack/config.base.js

I want to merge this change because it is really annoying to be unable to build project in development environment without resolving all type and lint errors. Also speeds up build a little. 

Move linting and typechecking to separate process

---

src/components/OverlayManager/Cart/Cart.tsx

It fixes the error in cart overlay when missing variants. #715
1) create a function for checking if there are missing variants in item array
2) adding a loader when there is an item with missing variant

fix missing variants error in cart overlay

---

package-lock.json
package.json

I want to merge this change because... it removes unused `mlx90363` lib from dependencies

Remove mlx90363 lib

---

Dockerfile

I want to merge this change because... it adds build variables used for production build to dockerfile 

Add build variables to dockerfile

---

.circleci/config.yml
.github/workflows/test.yml
.gitignore
package-lock.json
package.json

Migrate to GH Actions

---

package-lock.json
package.json

Fix SDK resolving for docker-based platform. Temporary fix because that would require updating npm registry each time SDK is updated.

Fix SDK resolving

---

src/@next/components/organisms/AddressForm/AddressFormContent.tsx
src/@next/components/organisms/AddressForm/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutAddress/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutPayment/__snapshots__/stories.storyshot

fix #770
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill#address

Fix address autocomplete

---

src/@next/components/atoms/Input/Input.tsx
src/@next/components/atoms/Input/__snapshots__/stories.storyshot
src/@next/components/atoms/Input/styles.ts
src/@next/components/atoms/InputLabel/index.ts
src/@next/components/atoms/InputLabel/styles.ts
src/@next/components/molecules/ResetPasswordForm/__snapshots__/stories.storyshot
src/@next/components/molecules/TextField/__snapshots__/stories.storyshot
src/@next/components/organisms/AddressForm/__snapshots__/stories.storyshot
src/@next/components/organisms/BraintreePaymentGateway/__snapshots__/stories.storyshot
src/@next/components/organisms/CartRow/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutAddress/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutPayment/__snapshots__/stories.storyshot
src/@next/components/organisms/CreditCardForm/__snapshots__/stories.storyshot
src/@next/components/organisms/DiscountForm/__snapshots__/stories.storyshot

fix input autofill styles in Address form

---

package-lock.json
src/components/OverlayManager/Search/gqlTypes/SearchResults.ts
src/components/OverlayManager/Search/queries.ts

Remove deprecated url field from product

---

CHANGELOG.md
README.md

Bumps version after recent release.

Bump version to 2.10.3

---

.storybook/main.js
CHANGELOG.md

I want to merge this change because it now supports eslint and react-intl auto id plugin.

Fix storybook config

---

src/@sdk/api/APIProxy.ts

I want to merge this change because it fixes type errors introduced in 2.10.3

Fix type errors

---

CHANGELOG.md
README.md

Bump version to 2.10.4

---

CHANGELOG.md
package-lock.json
package.json

I want to merge this change because it fixes bug causing passwords to be stored in apollo cache, that means in localStorage.

Update sdk to newest version

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test-env-cleanup.yml
.github/workflows/test-env-deploy.yml

Setup test environment deployment workflow

---

cypress/.eslintrc
cypress/elements/category/category-page.js
cypress/elements/filters-left-menu/filters-menu.js
cypress/elements/main-header/header-selectors.js
cypress/elements/saleor-account/login-selectors.js
cypress/integration/category/filters_and_sort_bar.js
cypress/integration/category/product_list.js
cypress/integration/main_menu/login_form.js
cypress/integration/main_menu/search.js
cypress/integration/user_account/user_orders_history.js
cypress/support/category/index.js
cypress/support/login/index.js
cypress/tsconfig.json
package-lock.json
package.json

I want to merge this change because I 've updated existing tests by adding data cy to the variables which make tests reusable.
API_URI=https://pwa.demo.saleor.rocks/graphql/

Refactor of existing tests

---

cypress/integration/category/product_list.js
cypress/integration/main_menu/login_form.js
cypress/integration/main_menu/search.js
cypress/integration/user_account/user_orders_history.js
package-lock.json

I have updated and xited existing cypress tests
API_URI=https://pwa.demo.saleor.rocks/graphql/

Update and xit existing cypress tests

---

.github/workflows/test.yml
package-lock.json
package.json

https://github.com/mirumee/saleor-dashboard/pull/586

Unify dashboard and storefront lint commands and actions

---

.github/workflows/test-env-deploy.yml

Remove edited from actions that deploy testenv

---

cypress/elements/saleor-account/login-selectors.js
cypress/fixtures/valid_user.json
cypress/integration/category/filters_and_sort_bar.js
cypress/integration/main_menu/login_form.js
cypress/support/category/index.js
cypress/support/commands.js
cypress/support/generate.js

I want to merge this change because I have Added new register test, change the path to the stg

Added new register test, change the path to the stg

---

cypress/fixtures/valid_user.json
cypress/integration/main_menu/login_form.js
cypress/integration/user_account/user_orders_history.js
cypress/support/login/index.js

I want to merge this change because this PR hides all test login passwords.

Add local env for passwords

---

src/@next/README.md

I want to merge this change because... it removes outdated note from the `@next` readme.

Update @next readme

---

cypress/elements/main-header/header-selectors.js
cypress/elements/products/checkout-selectors.js
cypress/elements/saleor-account/my-account-selectors.js
cypress/integration/products/order-history.js
cypress/support/checkout/index.js
cypress/support/product/index.js

I want to merge this change because it adds a new test for checking an order

Check order details test

---

locale/defaultMessages.json
src/userAccount/views/OrderDetails/Page.tsx

I want to merge this change because... it change nr to no.

Change nr to no.

---

README.md
cypress.json

I want to merge this change because I added a cypress readme

Add cypress readme and ignore all file changes

---

.gitignore
cypress.json
cypress/elements/main-header/header-selectors.js
cypress/elements/main-header/my-account-selectors.js
cypress/integration/main_menu/personal_details.js
cypress/integration/products/order-history.js
src/@next/components/atoms/Attribute/Attribute.tsx
src/@next/components/atoms/Attribute/__snapshots__/stories.storyshot
src/@next/components/atoms/Attribute/stories.tsx
src/@next/components/atoms/Attribute/test.tsx
src/@next/components/atoms/Attribute/types.ts
src/@next/components/molecules/AccountTabTiles/AccountTile.tsx
src/@next/components/molecules/AccountTabTiles/PasswordTile.tsx

I want to merge this change because it edits personal details test

Add edit personal details test

---

src/components/ProductDescription/index.tsx

fix https://github.com/mirumee/saleor-storefront/issues/857
also stop zeroing quantity after adding to cart. fix #796

Prevent adding negative quantity to cart

---

cypress/elements/products/checkout-selectors.js
cypress/elements/products/search-products-selectors.js
cypress/integration/main_menu/search.js
cypress/integration/products/buy_a_product.js
cypress/integration/products/order-history.js
cypress/support/commands.js
cypress/support/product/index.js

I want to merge this change because I want to add a test for checkout as a not logged user  and for not shipping items

add a test for checkout as a not logged user and for not shipping items

---

locale/defaultMessages.json
src/@next/components/atoms/DemoBanner/DemoBanner.tsx
src/components/Breadcrumbs/index.tsx
src/components/MainMenu/MainMenu.tsx
src/components/MobileNav/NavList.tsx
src/components/Select/SelectOptionsList.tsx
src/intl.ts

I want to merge this change because it adds some lacking localizations. Upload to Transifex will be needed.

Lacking localizations

---

.github/workflows/test-env-deploy.yml

API_URI can now contain dashes.
API_URI=https://adyen-lock-checkout-complete.api.saleor.rocks/graphql/

Updated test storefront deployment to allow dashes

---

CHANGELOG.md
src/views/Collection/Page.tsx
src/views/Collection/View.tsx
src/views/Collection/gqlTypes/CollectionProducts.ts
src/views/Collection/queries.ts

I want to merge this change because... it updates collection products query.
API_URI=https://add-searchable-and-available-for-purchase-flags-to-product.api.saleor.rocks/graphql/

Update collection products query

---

CHANGELOG.md
package-lock.json
package.json
src/@next/components/molecules/ProductTile/fixtures.ts
src/@next/components/molecules/ProductTile/types.ts
src/@next/components/molecules/Thumbnail/types.ts
src/@next/components/organisms/ProductList/ProductList.tsx
src/@next/components/organisms/ProductList/fixtures.ts
src/@next/components/organisms/ProductList/types.ts

I want to merge this change because... it adds changes introduced in https://github.com/mirumee/saleor-sdk/pull/26. Fixes https://github.com/mirumee/saleor-storefront/issues/853

Fix checkout refreshing

---

locale/defaultMessages.json
src/components/ProductDescription/index.tsx
src/intl.ts

I want to merge this change because... it changes purchase availability on text.

Fix purchase availability on text

---

src/sw.js

I want to merge this change because... it prevent `/plugins` path from caching.

Add plugins to blocklist

---

src/@next/components/atoms/Radio/__snapshots__/stories.storyshot
src/@next/components/atoms/Radio/styles.ts
src/@next/components/organisms/CheckoutShipping/CheckoutShipping.tsx
src/@next/components/organisms/CheckoutShipping/__snapshots__/stories.storyshot
src/@next/components/organisms/CheckoutShipping/styles.ts
src/@next/components/organisms/DummyPaymentGateway/__snapshots__/stories.storyshot
src/@next/components/organisms/PaymentGatewaysList/__snapshots__/stories.storyshot

I want to merge this change because... it fixes not centered radio button style.
Before:
After:

Fix radio button style

---

src/components/CartTable/ProductRow.tsx
src/userAccount/views/OrderDetails/Page.tsx

I want to merge this change because... it fixes the order line total price.

Fix order line total price

---

cypress/support/product/index.js

I want to merge this change because... it fixes failing cypress test.
API_URI=https://fix-for-avatax-and-digital-product-without-charge-taxes.api.saleor.rocks/graphql/

Fix no shippable product test

---

.github/workflows/test-env-deploy.yml
package.json
src/sw.js

Add build-storybook command

---

package-lock.json
package.json

Update SDK dependency with fix to solve infinite loading

---

README.md

I want to merge this change because it solves #896, #523, #894 and possibly more in the future.
Currently it gives a general idea of how the Storefront is built and where to make adjustments. New users of the `Saleor-Storefront` can get a sense of where to start instead of immediately posting to the issue tracker.
PR does not affect UI or UX.
Credit goes to: @cyberdemic
From: [spectrum](https://spectrum.chat/saleor/saleor-storefront/modifying-the-storefront~c1955 …

Add information about modifying the Storefront

---

CHANGELOG.md
src/@next/components/organisms/CheckoutAddress/CheckoutAddress.tsx
src/@next/components/organisms/CheckoutAddress/types.ts
src/@next/pages/CheckoutPage/subpages/CheckoutAddressSubpage.tsx

fix checkout address view

---

CHANGELOG.md
src/@next/components/organisms/CheckoutAddress/CheckoutAddress.tsx
src/@next/components/organisms/CheckoutAddress/types.ts
src/@next/pages/CheckoutPage/subpages/CheckoutAddressSubpage.tsx

Original PR: #909 by @Konstantinos
* fix checkout address view
Co-authored-by: “Konstantinos <“kostas.christomanos@gmail.com”>
Fixes #908

QA for fix checkout address view (#909)

---

CHANGELOG.md
README.md
config/webpack/config.base.js
config/webpack/config.dev.js
config/webpack/config.prod.js

I want to merge this change because it adds static url configuration. 

Static URL support

---

README.md
app.json
cypress.json
src/@next/components/atoms/DemoBanner/DemoBanner.tsx
src/@next/components/atoms/DemoBanner/__snapshots__/stories.storyshot

Fix demo domain

---

src/views/Collection/View.tsx

I want to merge this change because i found bug, and button LoadMore was not worked on Collection Pages.

fix bug with LoadMore button for collection page;

---

src/views/Collection/View.tsx

Move changes from PR #924 to master.

Fix bug with LoadMore button for collection page

---

package-lock.json
package.json
src/@next/components/molecules/ProductTile/fixtures.ts
src/@next/components/molecules/ProductTile/types.ts
src/@next/components/organisms/ProductList/fixtures.ts
src/@next/components/organisms/ProductList/types.ts
src/@next/types/IProduct.ts
src/@next/types/index.ts

I want to merge this change because... it updates SDK version to the latest 0.1.5

Update SDK to v.0.1.5

---

CHANGELOG.md
README.md
package-lock.json
package.json

Update changelog and version numbers after release.

Update after release

---

src/app/App.tsx
src/components/MainMenu/MainMenu.tsx
src/components/MainMenu/NavDropdown.tsx
src/components/MainMenu/scss/index.scss
src/components/Overlay/scss/index.scss

I want to merge this change because... it fixes the navigation glitch when storefront demo mode is used.

Fix navigation glitch in demo mode

---

.github/workflows/test-env-deploy.yml

I want to fix the Storybook build issue that can be seen in PR https://github.com/mirumee/saleor-storefront/pull/938.

Increase memory size for Storybook build

---

.github/workflows/test-env-cleanup.yml
.github/workflows/test-env-deploy.yml

Drop set-env in favor of set-output

---

src/views/Collection/View.tsx
src/views/Collection/gqlTypes/Collection.ts
src/views/Collection/gqlTypes/CollectionProducts.ts
src/views/Collection/queries.ts

I want to merge this change because collections are not rendering with multichannel api.

Add channel parameter to the collection queries

---

README.md

there were several typo errors

docs: fixed small typo errors in readme

---

.github/workflows/deploy-staging.yaml

Deploy to staging after merge to master

---

.github/workflows/deploy-staging.yaml

Added missing trailing slash to staging endpoint

---

Dockerfile.dev
README.md

Update readme and dev dockerfile

---

.github/workflows/deploy-staging.yaml

Fix deploy staging action

---

.github/workflows/deploy-staging.yaml
.github/workflows/test-env-deploy.yml
.github/workflows/test.yml

Fix env filename typo in gh actions

Fix env filename typo in gh actions

---

.github/workflows/deploy-staging.yaml
.github/workflows/test-env-deploy.yml
.github/workflows/test.yml
README.md

Fix gh actions workflows

---

.github/PULL_REQUEST_TEMPLATE.md

Update API url

---

package-lock.json
package.json
src/components/ShopProvider/context.ts

Bump SDK and drop geolocalization query that was removed in API.
API_URI=https://master.staging.saleor.cloud/graphql/

Update SDK version

---

README.md

I want to merge this change because it updates readme.
API_URI=https://master.staging.saleor.cloud/graphql/

Update readme note

---

.github/workflows/deploy-staging.yaml
cypress/integration/products/buy_a_product.js
cypress/integration/products/order-history.js

Fix staging deployment workflow

---

.github/workflows/deploy-staging.yaml

Use stategy matrix to handle mutiple staging builds

---

Procfile
package.json

I want to fix the Heroku deployment for storefront, as experienced by https://github.com/mirumee/saleor-storefront/issues/1000.

Fix package.json and Procfile to allow Heroku deployments

---

CHANGELOG.md
src/userAccount/views/OrderDetails/Page.tsx

I want to merge this change to correct order number formatting.

 Change order number format
