saleor/saleor-storefront

webpack.config.js
close #139 
Apparently iOS devices uses `appName` even if it's too long and `shortAppName` is provided.
So just changed `Saleor e-commerce` to `Saleor`.
Also, removed no-icon generation for Yandex and the other one. It seems like a default configuration leftover, and I see no reason why we should not generate it.
Lack of icon was not a problem anymore (double checked on pwa.getsaleor.com) not sure what was the cause. 
=> Fix PWA on iPhone

.circleci/config.yml
This PR changes CircleCI config to only deploy to S3 when a tag was pushed.
=> Trigger deploy only when tag was pushed

CHANGELOG.md, src/components/ProductDescription/scss/index.scss
This PR fixes the overflow image in product description.
Before:
After:
=> Set max width of images in product description as 100%

src/checkout/context.tsx, src/components/CartProvider/context.ts, src/components/Overlay/context.tsx, src/components/ShopProvider/context.ts, src/components/User/context.tsx
Alternatively display names can be shorter by dropping the `Context` at the end since context nodes are always followed by  `.Provider` or `.Consumer` but such option might be less explicit.
=> Added context display name for better readability in devtools

CHANGELOG.md, src/userAccount/views/OrderDetails/Page.tsx, src/userAccount/views/OrderDetails/queries.ts, src/userAccount/views/OrderDetails/types/Order.ts, src/userAccount/views/OrderDetails/types/OrderById.ts, src/userAccount/views/OrderDetails/types/OrderByToken.ts, src/userAccount/views/OrderDetails/types/OrderDetail.ts, types/globalTypes.ts
Instead of displaying raw statuses I changed the query to fetch "status displays". Also fixed calculating of order line amount which should rely on data returned by order line itself, not variant data.
=> Fix calculating orderline amount and order statuses

CHANGELOG.md, src/components/CachedImage/CachedImage.tsx
=> Added images to cache

src/views/Article/View.tsx
it fixes #308 
When accessing https://pwa.getsaleor.com/page/whatever the page was crashing as "whateverpage" could not be queried and there was no redirect done for that particular case.
=> Add redirect to 404 in case of incorrect page address

CHANGELOG.md, src/components/App/scss/_utils.scss, src/components/CheckoutLogin/CheckoutAsGuest.tsx, src/components/CheckoutLogin/ResetPasswordForm.tsx, src/components/CheckoutLogin/SignInForm.tsx, src/components/CheckoutLogin/index.tsx, src/components/CheckoutLogin/scss/index.scss, src/components/Overlay/context.tsx, src/components/OverlayManager/Login/ForgottenPassword.tsx, src/components/OverlayManager/Login/index.tsx, src/components/OverlayManager/Login/scss/index.scss, src/components/OverlayManager/Manager.tsx, src/components/PasswordResetForm/scss/index.scss
I want to merge this change because... it fixes #218 
"create an account" link has been added:
I modified Login component so now it can accept prop for setting active tab - user is presented with **Register** tab when clicking "create an account" instead of **Sign in** tab
=> Add link for creating account for anonymous users

CHANGELOG.md, src/components/LoginForm/index.tsx, src/components/OverlayManager/Login/RegisterForm.tsx, src/components/OverlayManager/Login/index.tsx
Fixes #322  The code is documented (docstrings, project documentation).
=> Fix login and registration form not hidding automatically

.plop/templates/reactComponent.tsx.hbs
Adds explicit `Props` type on argument inside React component template. When destructuring inside argument, TS allows for any default value to be assigned resulting in an union type.
=> [refactor] Adjust react component plop template

.storybook/preview-head.html, src/globalStyles/scss/variables.scss
Changes very bold font weight to 900 from 800 in template,
it adds montserrat font while using storybook.
Before
After:
=> Add link to montserrat font so it works in storybook

.plop/index.js, .plop/templates/reactComponentStory.tsx.hbs
Fixes plop generator for storybook stories - it now uses `storiesOf` instead of `createStory`
=> Add changes to plo for generating stories

src/views/Category/Page.tsx, src/views/Search/index.tsx
Fixes #299 
With this correction, when the filters don't match any product, the filters keep open and the user can correct it. The change affects 2 pages:
1) The "Search" page:
2) The "Categories" page:
1. [N/A] All visible strings are translated with proper context.
1. [N/A] All data-formatting is locale-aware (dates, numbers, and so on).
1. [X] The changes are tested.
1. [X ] The code is documented (docstrings, project documentation).
=> fix issue #299 - display filters when no product was found

CHANGELOG.md, src/@next/components/atoms/PlaceholderImage/PlaceholderImage.tsx, src/@next/components/atoms/PlaceholderImage/index.ts, src/@next/components/atoms/PlaceholderImage/stories.tsx, src/@next/components/atoms/PlaceholderImage/types.ts, src/@next/components/atoms/index.ts, src/@next/components/molecules/CachedImage/CachedImage.tsx, src/@next/components/molecules/Thumbnail/Thumbnail.tsx, src/components/ProductListItem/index.tsx, src/views/Product/View.tsx
I probably explained  the starting point of my work in [this comment](https://github.com/mirumee/saleor-storefront/issues/489#issuecomment-540053021) in issue #489 .
I created  a `PlaceholderImage` component that I replaced where `Thumbnail` and `CachedImage` were using it, trying to leave the existing logic unaffected and removing unnecessary _<img>_ tags.
`Thumbnail` now checks if the `thumbnail` object is defined and, in case it is not, it returns the `PlaceholderImage` directly without waiting for the exception to trigger `CachedImage`'s fallback
Fixes #489
1. [ ] The code is …
=> Show image placeholders #489

src/components/OverlayManager/Search/scss/index.scss, src/components/TextField/scss/index.scss
Quickfix for search overlay - icons are not shown in middle of the screen anymore
=> Fix search bar

CHANGELOG.md, src/components/ProductsFeatured/index.tsx, src/core/SEO/Homepage/structuredData.tsx, src/views/Home/Page.tsx, src/views/Home/View.tsx
I want to merge this change because it should fix #508. 
When no data exist in the database:
=> Ordinary conditional checks when no data exist to make storefront works

config/webpack/config.base.js
Exception will be thrown if no API_URI env variable is not set
=> Add exception to webpack when API_URI is not set

src/checkout/views/Payment/View.tsx
Firefox will run default actions for 'submit' buttons unless it's told not to.
This means that the 'continue to review your order' will not work in Firefox and will instead refresh the page.
[See here](https://stackoverflow.com/questions/49587933/firefox-doesnt-preventing-dispatched-submit-event) for more.
=> Fix review order button for firefox

app.json
It fixes heroku deployment file. File was pointing to old url(`https://demo.getsaleor.com/graphql/`) but it should point to `https://pwa.demo.saleor.rocks/graphql/`
=> Fix link pointing to demo instance for heroku deploy

src/checkout/components/AddressPicker/Picker.tsx, src/checkout/components/UserAddressSelector/UserAddressSelector.tsx, src/checkout/types.ts, src/components/ShippingAddressForm/AddNewShippingAddressForm.tsx, src/components/ShippingAddressForm/types.ts
I want to merge this change because... 
- it removes email field from checkout shipping form address addition modal if user is logged in,
- it takes instead automatically logged in user email and saves it in new address
Before:
After:
=> Remove email in checkout shipping for logged in user

.storybook/preview-head.html, src/globalStyles/scss/index.scss, src/index.html
I want to merge this change because... it adds preconnect to fetch css file describing required fonts. It will cause establish early connections to that file, what might be used in future rendering without blocking it due to required connection establishment.
Another improvement would be moving font source imports to Google fonts, although it is not yet available there due to not full support of this font rendering in modern browsers - https://github.com/google/fonts/pull/1908#issuecomment-580509162 - we might expect it in the future.
=> Preload css for Inter font

src/@sdk/index.ts, src/@sdk/queries/index.ts, src/@sdk/queries/shop.ts, src/@sdk/queries/types/GetShop.ts, src/@sdk/react/queries.ts, src/components/ShopProvider/index.tsx
It fixes landing page queries. Right now storefront was hitting backend with 2 graphql requests. Now it only uses 1.
=> Use sdk for fetching shop details

.dockerignore, .gitignore
I want to merge this change because you cannot build the project using docker if you have already done `npm install` on host. Compose of platform will hang because too wide file context it's trying to send to docker daemon and it takes ages without need for that (`npm install` it's done within container anyway in both dockerfiles)
=> Add .dockerignore file so you can build storefront with node modules present

src/checkout/views/Review/Summary.tsx, src/checkout/views/Review/View.tsx
I want to merge this change because... it fixes #628 app crash when product with no shopping method is available in checkout review.
=> Fix failing checkout review with digital products

README.md
it removes information which is not valid anymore(about translations) from README.md file
=> Remove translation information from README

src/constants.ts
I want to merge this change because it's unused code anyway. 
`process.env.API_URI` is ensured to have value on the build level.
=> Remove unreachable code

src/@next/hooks/useServiceWorker.tsx, src/@sdk/global.d.ts, webpack.d.ts
I want to merge this change because... it unregisters service worker to run properly Cypress tests.
=> Unregister service worker for Cypress

src/components/CartProvider/utils.ts
This fixes the issue in gross and net amount in the returned totalPrice when product quantity changes. #663 
Before
After
=> totalPrice returned fix  #663 

src/components/OverlayManager/Cart/Cart.tsx, src/components/OverlayManager/Cart/scss/index.scss
I want to merge this change because it adds missing shipping and total prices, as well as promo code discount to cart sidebar. If shipping and promo code is not available, then it will be hidden.
=> Fix cart sidebar prices

src/@next/components/organisms/ProductVariantPicker/ProductVariantAttributeSelect.tsx
I want to merge this change because it disables undesired keyboard opening on mobile devices when selecting product variant attribute.
- iOS
- Android
- iOS
- Android
=> Disable keyboard opening when selecting product variant

config/webpack/config.base.js, config/webpack/config.worker.js, src/@next/hooks/useServiceWorker.tsx
I want to merge this change because it fixes #674, by registering service worker only if it built with webpack.
=> Register service worker only if it is built

config/webpack/config.base.js, package-lock.json, package.json, src/constants.ts, src/index.tsx
This adds Sentry and Sentry Performance support to the storefront.
New env variables:
- `SENTRY_DSN`: if set to a Sentry DSN, enables Sentry support
- `SENTRY_APM`: if set to a float, controls the percentage of performance traces that are reported (set to "0.5" for 50% of all traces, "0.1" for 10% and so on)
=> Add support for Sentry and performance tracing

src/@next/components/organisms/CartRow/CartRow.tsx, src/@next/components/organisms/CartRow/fixtures.ts, src/@next/components/organisms/CartRow/types.ts, src/@next/pages/CartPage/CartPage.tsx
It adds hyperlink functionality to cart row in cart page, 
fixes issue #742
=> add product hyperlink in cart page

CHANGELOG.md, src/@next/components/organisms/CartRow/__snapshots__/stories.storyshot, src/@next/components/organisms/CartRow/fixtures.ts, src/@next/components/organisms/CartRow/stories.tsx, src/@next/components/organisms/CartRow/test.tsx
I want to merge this change because it fixes test errors introduced in #745 
=> Fix CartRow tests

.gitignore, .prettierignore, CHANGELOG.md, src/components/Footer/gqlTypes/SecondaryMenu.ts, src/components/MainMenu/gqlTypes/MainMenu.ts, src/views/Category/gqlTypes/Category.ts, src/views/Collection/gqlTypes/Collection.ts, src/views/Search/gqlTypes/SearchProducts.ts
I want to merge this change because it prevents prettier from linting generated files.
=> Do not use prettier on generated files

CHANGELOG.md, locale/defaultMessages.json, package-lock.json, package.json, src/@next/components/molecules/OrderTabel/types.ts, src/@next/pages/OrdersHistory/OrdersHistory.tsx, src/userAccount/views/OrderDetails/Page.tsx, src/userAccount/views/OrderDetails/View.tsx, src/userAccount/views/OrderDetails/scss/index.scss
I want to merge this change because it adds the possibility to download invoice from the popup menu in the order details view for logged in user.
**PR intended to be tested with API branch:** 
https://github.com/mirumee/saleor/pull/5732
**PR intended to be tested with SDK branch:** 
https://github.com/mirumee/saleor-sdk/pull/13
=> Download invoice for order

src/views/Category/queries.ts, src/views/Collection/queries.ts, src/views/Search/queries.ts
I want to merge this change because... it makes use of the `filterableInStorefront` configuration parameter and presents only selected filters in storefronts sidebar.
=> Add use of filterableInStorefront in Sidebar

CHANGELOG.md, src/@next/components/organisms/PaymentGatewaysList/PaymentGatewaysList.tsx
I want to merge this change because it handles payment gateways that are unsupported simply by omitting them.
=> Do not throw error if unsupported payment gateway found

CHANGELOG.md, tsconfig.json
I want to merge this change because... it helps VS Code to auto-import with shorter aliases, by moving less nested paths down in the tsconfig paths:
instead of autoimport from `@temp/@next/types` just do it from `@types`.
=> Fix tsconfig aliases

config/webpack/config.worker.js, src/app/routes/AppRoutes.tsx, src/sw.js
storefront is hijacking csv files export.
=> Do not cache csv and pdf in service worker

CHANGELOG.md, src/@next/components/organisms/CheckoutPayment/CheckoutPayment.tsx, src/@next/components/organisms/CheckoutPayment/__snapshots__/stories.storyshot, src/@next/components/organisms/CheckoutPayment/stories.tsx, src/@next/components/organisms/CheckoutPayment/test.tsx, src/@next/components/organisms/CheckoutPayment/types.ts, src/@next/components/templates/Checkout/Checkout.tsx, src/@next/components/templates/Checkout/__snapshots__/stories.storyshot, src/@next/components/templates/Checkout/stories.tsx, src/@next/components/templates/Checkout/styles.ts, src/@next/components/templates/Checkout/types.ts, src/@next/pages/CheckoutPage/CheckoutPage.tsx, src/@next/pages/CheckoutPage/subpages/CheckoutPaymentSubpage.tsx
I want to merge this change because... it makes payment gateways persisted for all the checkout steps and hides them through CSS if they shouldn't be displayed.
=> Hoist payment gateways for the whole checkout

CHANGELOG.md, src/@next/components/atoms/DropdownMenu/DropdownMenu.tsx, src/@next/components/atoms/DropdownMenu/types.ts, src/@next/components/molecules/AddressTile/AddressTile.tsx, src/@next/components/molecules/AddressTile/__snapshots__/stories.storyshot, src/@next/components/organisms/AddressGrid/__snapshots__/stories.storyshot
I want to merge this change because it allows testing setting billing and shipping addresses.
=> Add test tags to address book

CHANGELOG.md, package-lock.json, package.json, src/account/AddressBook/AddressBook.tsx
I want to merge this change because it fixes bug when user tries to do anything with the non-existent address, refreshing the cache and removing it.
=> Refresh user data if mutation fails

CHANGELOG.md, locale/defaultMessages.json, package-lock.json, package.json, src/@next/components/organisms/AdyenPaymentGateway/AdyenPaymentGateway.tsx, src/@next/components/organisms/AdyenPaymentGateway/__snapshots__/stories.storyshot, src/@next/components/organisms/AdyenPaymentGateway/fixtures.ts, src/@next/components/organisms/AdyenPaymentGateway/index.ts, src/@next/components/organisms/AdyenPaymentGateway/stories.tsx, src/@next/components/organisms/AdyenPaymentGateway/test.tsx, src/@next/components/organisms/BraintreePaymentGateway/BraintreePaymentGateway.tsx, src/@next/components/organisms/PaymentGatewaysList/PaymentGatewaysList.tsx, src/@next/components/organisms/PaymentGatewaysList/stories.tsx, src/@next/components/organisms/PaymentGatewaysList/test.tsx, src/@next/components/organisms/PaymentGatewaysList/types.ts, src/@next/components/organisms/StripePaymentGateway/StripePaymentGateway.tsx, src/@next/components/organisms/index.ts, src/@next/pages/CheckoutPage/CheckoutPage.tsx, src/@next/pages/CheckoutPage/CheckoutRouter.tsx, src/@next/pages/CheckoutPage/subpages/CheckoutReviewSubpage.tsx, src/@next/types/ICardData.ts, src/core/config.ts, webpack.d.ts
I want to merge this change because... it adds Adyen payment gateway.
Please test it on `127.0.0.1:3000`, as Adyen has client key configured for this particular address, it will not work with `localhost:3000`.
`master` (or `adyen_integration` already merged)
=> Add adyen gateway

CHANGELOG.md, src/components/ProductDescription/index.tsx, src/components/ProductListItem/index.tsx, src/views/Product/View.tsx
I want to merge this change because... it fixes storefront crashes when the price range is null.
where `index.tsx` was referenced to
=> Fix crash on null price range

src/globalStyles/scss/index.scss
This fixes the page shift/jitter that happened when using the navbar. To do this, I calculate the scrollbar width, use a negative margin-right to add it to the body without affecting the sites formatting/styling, and then hide the horizontal overflow that it creates.
Use the https://demo.saleor.io/ for an example of the visual shift that happens when using the navbar. It's hard to see the difference in pictures versus seeing it in action.
#861 …
=> fix page shift when navbar is used

cypress/integration/products/buy_a_product.js
I want to merge this change because... it fixes test email faker to fix failing e2e tests.
It replaces the following email whitespaces:
=> Fix test email faker

CHANGELOG.md, package-lock.json, package.json, src/@next/hooks/useCheckoutStepState.ts, src/@next/pages/CheckoutPage/CheckoutPage.tsx, src/@next/pages/CheckoutPage/CheckoutRouter.tsx, src/@next/types/ITaxedMoney.ts, src/@next/utils/core.ts, src/@next/utils/money.test.ts, src/@next/utils/money.ts
I want to merge this change because... it
- redirects the user to shipping step if payment amount is not equal to checkout total price (e.g. item was added to the cart) and thanks to it payment may be recreated with proper payment amount
- still preserves the possibility for user to go to payment step when shipping was set already
- fixes the case when user removes all items requiring shipping, leaving only digital product, when active path was `/checkout/shipping` and user was not redirected to other possible step
- fixes the case when user removes all items requiring shipping, leaving only digital product and shipping method was still wrongly set, while it shouldn't exist anymore and total price should be updated
- shipping method is now updated after adding/removing item to cart, and …
=> Require payment recreate when payment price is wrong

CHANGELOG.md, src/app/App.tsx, src/app/Notifications.tsx, src/index.tsx, src/views/Category/View.tsx, src/views/Collection/View.tsx, src/views/Product/View.tsx, src/views/Search/View.tsx
I want to merge this change because... it shows a loading state when the token is refreshing due to token expiration or it is verifying when the application starts - all the token expiration and verification logic is delegated to the SDK, implemented in https://github.com/mirumee/saleor-sdk/pull/29 and https://github.com/mirumee/saleor-sdk/pull/30 respectively.
⚠️ To test if the functionality works make sure to have HTTPS connection on both frontend and backend and backend to have `SameSite=None` and `Secure` flags set in `set-cookie` header received from `tokenCreate` mutation (`saleor/saleor/core/middleware.py`) - testing with cross-site domains requires HTTPS and Secure flag set to mitigate network attacks [https://web.dev/samesite-cookies-explained](https://web.dev/samesite-cookies-exp …
=> Handle JWT token refreshing and verifying

CHANGELOG.md, locale/defaultMessages.json, src/components/OverlayManager/Cart/Cart.tsx, src/components/OverlayManager/Cart/scss/index.scss
I want to merge this change because... it fixes hiding item in the cart sidebar and items quantity message.
Previously it was sometimes hidden by prices amount (when the cart list was scrolled to the very end):
Now:
=> Fix cart sidebar style

CHANGELOG.md, src/@next/pages/CheckoutPage/CheckoutPage.tsx, src/core/utils.ts, webpack.d.ts
It fixes the issue https://github.com/mirumee/saleor-storefront/issues/889
=> [Fix] Generate site map

CHANGELOG.md, package.json, src/components/OverlayManager/Search/ProductItem.tsx, src/components/OverlayManager/Search/__snapshots__/stories.storyshot, src/components/OverlayManager/Search/scss/index.scss, src/components/OverlayManager/Search/stories.tsx
I want to merge this change because it fixes issue when searching for a product that has no category and the app crashes
[SALEOR-1398](https://app.clickup.com/t/2549495/SALEOR-1398)
=> Add default value to product item category in case none is provided

src/@next/components/organisms/AddToCartSection/AddToCartSection.tsx, src/@next/components/organisms/AddToCartSection/stories.tsx, src/views/Product/Page.tsx
I want to merge this change because it fixes product details page not update'ing images to product variant images after variant is chosen
[SALEOR-1458](https://app.clickup.com/t/2549495/SALEOR-1458)
Product variant edit page:
Before:
After✨:
API_URI=https://test-deployment.api.saleor.rocks/graphql/
=> Fix images not displaying for variant

package-lock.json, package.json
Adjusts user checkout query which is now split into 2 queries (first returns list of tokens and the second queries the details)
https://app.clickup.com/t/2549495/SALEOR-1654
=> [1654] Use next SDK version (user channel token)

CHANGELOG.md, src/@next/components/molecules/OrderTabel/__snapshots__/stories.storyshot, src/@next/components/molecules/OrderTabel/styles.ts, src/@next/components/molecules/ProductTile/__snapshots__/stories.storyshot, src/@next/components/molecules/ProductTile/styles.ts, src/@next/components/organisms/ProductGallery/__snapshots__/stories.storyshot, src/@next/components/organisms/ProductGallery/styles.ts, src/@next/components/organisms/ProductList/__snapshots__/stories.storyshot
I want to merge this change because it:
- fixes product gallery preview height
- fixes thumbnail preview height on Order history
- fixes thumbnail height on listing of products
=> Saleor 1775 thumbnail size issues

.github/workflows/test.yml, CHANGELOG.md, cypress/elements/products/checkout-selectors.js, cypress/elements/products/products-selectors.js, cypress/support/product/index.js, src/views/Product/queries.ts
I want to merge this change because... it adds usage of only selection attributes in variant picker.
**PR intended to be tested with API branch:**  feature/file-uploads
https://github.com/mirumee/saleor/pull/6568
API_URI=https://feature-file-uploads.api.saleor.rocks/graphql/
=> Use only selection attributes in variant picker

CHANGELOG.md, package-lock.json, package.json, src/@next/components/organisms/CartSidebar/fixtures.ts, src/@next/components/organisms/ProductVariantPicker/fixtures.ts, src/components/CartTable/ProductRow.tsx, src/core/SEO/Product/structuredData.tsx, src/views/Product/gqlTypes/ProductDetails.ts, src/views/Product/gqlTypes/ProductVariantFields.ts, src/views/Product/gqlTypes/VariantList.ts, src/views/Product/queries.ts
This PR removes the deprecated `ProductVariant.isAvailable` field.
=> Drop ProductVariant.isAvailable field

src/views/Article/View.tsx, src/views/Product/View.tsx
I want to merge this change because it fixes pages / product details crashing when content or description fields are null
API_URI=https://master.staging.saleor.cloud/graphql/
=> Fix views crashing when description or content fields are null

Dockerfile.dev, nginx/dev.conf
I want to merge this change because I want to resolve the networking issue in the Saleor platform.
In nutshell:
- browser can reach API endpoint with "localhost:8000" URL
- ssr from within the container need to use "API:8000" URL
This change add nginx proxy for the dev container which proxy `localhost:8000` to `api:8000`.
=> Add nginx proxy for ssr in platform
